return {
	cmd = { "emmet-language-server", "--stdio" },
	filetypes = {
		"astro",
		"css",
		"eruby",
		"html",
		"htmlangular",
		"htmldjango",
		"javascriptreact",
		"less",
		"pug",
		"sass",
		"scss",
		"svelte",
		"templ",
		"typescriptreact",
		"vue",
	},
	init_options = {
		includelanguages = {},
		excludelanguages = {},
		extensionspath = {},
		preferences = {},
		showabbreviationsuggestions = true,
		showexpandedabbreviation = "always",
		showsuggestionsassnippets = false,
		syntaxprofiles = {},
		variables = {},
	},

	root_markers = { ".git" },
}
