#!/usr/bin/env bash
set -e

sudo pacman -S --needed \
    ttf-jetbrains-mono-nerd ttf-firacode-nerd ttf-cascadia-code-nerd \
    ttf-meslo-nerd ttf-hack-nerd noto-fonts noto-fonts-emoji

# Audio
sudo pacman -S --needed \
    pipewire pipewire-pulse pipewire-alsa wireplumber pavucontrol
systemctl --user enable --now pipewire pipewire-pulse wireplumber

# File directory
mkdir -p ~/.local/bin ~/Downloads ~/Documents ~/Desktop ~/dev ~/sandbox ~/Pictures ~/Music ~/Videos

# Base packages
sudo pacman -S --needed \
    ghostty waybar swww swaync tmux rofi hypridle hyprlock thunar \
    firefox zsh fzf \
    wl-clipboard cliphist network-manager-applet brightnessctl \
    playerctl nwg-look lazygit vlc swayimg zip unzip p7zip ripgrep \
    xdg-desktop-portal-gtk xdg-desktop-portal-hyprland

# For Thunar
sudo pacman -S --needed \
    gvfs gvfs-mtp gvfs-afc gvfs-gphoto2 gvfs-smb tumbler thunar-volman

# Chaotic AUR
if ! grep -q "\[chaotic-aur\]" /etc/pacman.conf; then
    sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
    sudo pacman-key --lsign-key 3056513887B78AEB
    sudo pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'
    sudo pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
    echo -e "\n[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist" | sudo tee -a /etc/pacman.conf
    sudo pacman -Sy
fi

# Paru
if ! command -v paru &>/dev/null; then
    sudo pacman -S --needed base-devel git
    cd /tmp
    git clone https://aur.archlinux.org/paru.git
    cd paru
    makepkg -si --noconfirm
    cd ~
fi

# AUR Packages
paru -S --needed neovim-git wlogout wl-clip-persist hyprshot

# Fonts
paru -S --needed maplemono-nf-cn-unhinted

# Clone dotfiles
cd ~/dev

if [ ! -d dotfiles ]; then
    git clone https://github.com/Hamiii23/dotfiles.git
fi

cp -r ~/dev/dotfiles/scripts/* ~/.local/bin/
curl -fsSL https://bun.sh/install | bash

cp -r ~/dev/dotfiles/ghostty ~/.config/

cp -r ~/dev/dotfiles/nvim ~/.config/
mkdir -p ~/.cache/nvim

cp -r ~/dev/dotfiles/rofi ~/.config/
cp -r ~/dev/dotfiles/swaync ~/.config/
cp -r ~/dev/dotfiles/waybar ~/.config/

cp ~/dev/dotfiles/.zshrc ~/.zshrc
cp ~/dev/dotfiles/.p10k.zsh ~/.p10k.zsh
cp ~/dev/dotfiles/.tmux.conf ~/.tmux.conf

cp -r ~/dev/dotfiles/gtk-3.0 ~/.config/
cp -r ~/dev/dotfiles/gtk-4.0 ~/.config/

if [ ! -d ~/.tmux/plugins/tpm ]; then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

~/.tmux/plugins/tpm/bin/install_plugins

# Change shell to Zsh
chsh -s "$(which zsh)"

# Docker
sudo pacman -S --needed docker docker-buildx docker-compose
sudo systemctl enable --now docker.service
sudo usermod -aG docker "$(whoami)"

# Theme
paru -S --needed gtk-engine-murrine sassc gnome-themes-extra \
    catppuccin-gtk-theme-git tela-icon-theme
