#!/usr/bin/env bash

MAX=25

if ! playerctl status &>/dev/null; then
    echo '{"text":" Nothing Playing","class":"stopped"}'
    exit 0
fi

STATUS=$(playerctl status)

case "$STATUS" in
Playing)
    ICON=""
    CLASS="playing"
    ;;
Paused)
    ICON=""
    CLASS="paused"
    ;;
*)
    echo '{"text":" Nothing Playing","class":"stopped"}'
    exit 0
    ;;
esac

TITLE=$(playerctl metadata --format '{{ title }}')

[ -z "$TITLE" ] && TITLE="Unknown Title"

TITLE=$(printf "%s" "$TITLE" | awk -v max="$MAX" '
{
    if (length($0) > max)
        print substr($0, 1, max) "…"
    else
        print
}')

printf '{"text":"%s %s","class":"%s"}\n' "$ICON" "$TITLE" "$CLASS"
