#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(
        tmux list-sessions -F "#{session_name}" 2>/dev/null |
            fzf --prompt="❯ " \
                --pointer="▶" \
                --border=rounded \
                --height=50% \
                --reverse \
                --preview='tmux list-windows -t {}' \
                --preview-window=right:50% \
                --color='bg+:#191724,bg:#000000,border:#26233a,fg:#e0def4,header:#908caa,hl+:#eb6f92,hl:#eb6f92,info:#908caa,pointer:#eb6f92,prompt:#eb6f92'
    )
fi

if [[ -z $selected ]]; then
    exit 0
fi

if [[ -z $TMUX ]]; then
    tmux attach -t "$selected"
else
    tmux switch-client -t "$selected"
fi
