#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/.config/ ~/dev ~/scripts ~/sandbox -maxdepth 1 -type d |
        fzf --prompt="❯ " \
            --pointer="▶" \
            --border=rounded \
            --height=50% \
            --reverse \
            --preview='ls -la {}' \
            --preview-window=right:50% \
            --color='bg+:#191724,bg:#000000,border:#26233a,fg:#e0def4,header:#908caa,hl+:#eb6f92,hl:#eb6f92,info:#908caa,pointer:#eb6f92,prompt:#eb6f92')
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
fi

if [[ -z $TMUX ]]; then
    tmux attach -t "$selected_name"
else
    tmux switch-client -t "$selected_name"
fi
