require("plugins.colorscheme")
require("plugins.oil")
require("plugins.comp")
require("plugins.conform")
require("plugins.harpoon")
require("plugins.snacks")
require("plugins.utils")
require("plugins.treesitter")
