vim.pack.add({
	{ src = "https://github.com/nvim-treesitter/nvim-treesitter", version = "master" },
})

require("nvim-treesitter.configs").setup({
	ignore_install = {},
	modules = {},
	auto_install = true,
	ensure_installed = {
		"json",
		"javascript",
		"typescript",
		"tsx",
		"go",
		"yaml",
		"html",
		"css",
		"python",
		"http",
		"prisma",
		"markdown",
		"markdown_inline",
		"svelte",
		"graphql",
		"bash",
		"lua",
		"vim",
		"dockerfile",
		"gitignore",
		"query",
		"vimdoc",
		"c",
		"java",
		"rust",
	},
	sync_install = false,
	highlight = { enable = true },
	indent = { enable = true },
	incremental_selection = {
		enable = true,
		keymaps = {
			init_selection = "<C-space>",
			node_incremental = "<C-space>",
			scope_incremental = false,
		},
	},
	additional_vim_regex_highlighting = false,
})
