vim.pack.add({
	{ src = "https://github.com/nvim-treesitter/nvim-treesitter", version = "master" },
})

require("nvim-treesitter.configs").setup({
	ignore_install = {},
	modules = {},
	auto_install = true,
	ensure_installed = {
		"json",
		"javascript",
		"typescript",
		"tsx",
		"go",
		"yaml",
		"html",
		"css",
		"python",
		"http",
		"prisma",
		"markdown",
		"markdown_inline",
		"bash",
		"lua",
		"vim",
		"dockerfile",
		"gitignore",
		"query",
		"vimdoc",
		"c",
		"rust",
	},
	highlight = { enable = true },
	indent = { enable = true },
})
